

name: GreenCart CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, greencart]

    steps:
      - name: Clean workspace
        run: rm -rf $GITHUB_WORKSPACE/*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # -------- SERVER --------
      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Test server (optional)
        working-directory: server
        run: npm test || echo "No server tests"

      # -------- CLIENT --------
      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: npm run build

      # -------- RESTART BACKEND --------
      - name: Restart backend with PM2
        working-directory: server
        run: |
          pm2 restart greencart-api || pm2 start server.js --name greencart-api
