name: GreenCart CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, greencart]

    steps:
      - uses: actions/checkout@v4

      - name: Verify Node & npm
        run: |
          node -v
          npm -v

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Test server (optional)
        run: |
          cd server
          npm test || echo "No server tests"

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build


